### ISSUE TITLE
Questions about testing Semantics tasks

### ISSUE THREAD

**Issue by qinhaijian23** [TOPO-EPFL/CrossLoc#3]
Hi scholars, hello everyone. When I am executing -- task semantics/depth/normal, regardless of whether I change the weight name you provided to mlr_encoder_ * or ckpt_iter_ *, the following error still appears, indicating that the information was not read correctly. How should this situation be resolved? If I execute -- task coord, this problem won't occur. Why is this?
"(crossloc) user@user:~/workspaces/CrossLoc$ python3 test_single_task.py naturescape --task semantics --uncertainty mle --section test_drone_real --network_in /media/user/Data/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place/
Namespace(fullsize=False, grayscale=False, hypotheses=64, inlieralpha=100, keywords=None, max_ckpt_iter=None, maxpixelerror=100, min_ckpt_iter=None, network_in='/media/slby/user/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place/', plot=False, save_pred=False, scene='naturescape', search_dir=False, section=['test_drone_real'], session='', task='semantics', threshold=10, tiny=False, uncertainty='MLE')
To load network weight from /media/user/Data/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place
With the keywords None, and min ckpt iter None, max ckpt iter None the following 1 network weight paths are retrieved:
Network weight #0: /media/user/Data/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place/ckpt_iter_crossloc_se_naturescape_in-place.net
==================== Evaluating network #1 / 1 ====================
Path: /media/user/Data/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place/ckpt_iter_crossloc_se_naturescape_in-place.net
Traceback (most recent call last):
  File "test_single_task.py", line 420, in <module>
    main()
  File "test_single_task.py", line 299, in main
    network = config_network(scene, task, tiny, grayscale, uncertainty, fullsize, network_path, num_enc=num_enc)
  File "/home/user/workspaces/CrossLoc/utils/evaluation.py", line 162, in config_network
    raise NotImplementedError
NotImplementedError"

**Comment by qiyan98** [comment]
Hi there,

Can you show me what your line 162 is?
`File "/home/user/workspaces/CrossLoc/utils/evaluation.py", line 162, in config_network
`

L162 in the code base is https://github.com/TOPO-EPFL/CrossLoc/blob/a9f9a3fbb6d6fb1edd82f38efe02b2ca9d6afeb0/utils/evaluation.py#L162, which does not involve `raise NotImplementedError`. I am not sure which statement invokes the error.

**Comment by qiyan98** [comment]
Oh I think it may be due to the ``--uncertainty`` argument at L102: https://github.com/TOPO-EPFL/CrossLoc/blob/a9f9a3fbb6d6fb1edd82f38efe02b2ca9d6afeb0/utils/evaluation.py#L102

Can you remove `--uncertainty mle` from your training command?

**Comment by qinhaijian23** [comment]
> Hi there, 嘿，你好
> 
> Can you show me what your line 162 is? 你能告诉我你的 162 号线是什么吗？ `File "/home/user/workspaces/CrossLoc/utils/evaluation.py", line 162, in config_network `
> 
> L162 in the code base is  代码库中的 L162 是
> 
> https://github.com/TOPO-EPFL/CrossLoc/blob/a9f9a3fbb6d6fb1edd82f38efe02b2ca9d6afeb0/utils/evaluation.py#L162
> 
> , which does not involve `raise NotImplementedError`. I am not sure which statement invokes the error.
> ，这不涉及。我不确定哪个语句调用了错误。

Hi,Teacher, thank you for taking the time out of your busy schedule to reply. My line 162 section is this: raise NotImplementedError
if uncertainty is None:
num_pos_channel = 0
elif uncertainty == 'MLE':
num_pos_channel = 1
else:
raise NotImplementedError
if task == 'semantics' and uncertainty is not None:
raise NotImplementedError
if task == 'semantics' and not fullsize:
raise NotImplementedError
I tried annotating some statements, but it didn't work. May I ask, teacher? What other possible problems are there?

**Comment by qinhaijian23** [comment]
> Can you remove `--uncertainty mle` from your training command?

Teacher, do you mean that I need to try the annotation method of "uncertainty='MLE '"? I tried once, but still couldn't get through. I'm sorry to bother you.

**Comment by qiyan98** [comment]
Hi, I mean you should try running the code without specifying `--uncertainty mle`. So in your terminal, try to run something like this:

```
python3 test_single_task.py naturescape --task semantics --section test_drone_real --network_in /media/user/Data/CrossLoc-Datasets/ckpt_CrossLoc_network_weights/naturescape/in-place/
```
